### ISSUE TITLE
Revise Database Schema

### ISSUE THREAD

**Issue by anikait-rao** [ctc-uci/the-literacy-project-backend#12]
Make a database schema diagram and revise the datatables. You guys may want to work with the group doing the PostgreSQL setup. Current doc is missing data and relations between data.

[How to design a DB schema](https://www.lucidchart.com/pages/database-diagram/database-schema)

Datatables: https://docs.google.com/document/d/11OQiiVDpT07Rk-jz0VY7yVKsAjqZC_97wewZR32cw6w/edit?usp=sharing

Requirements Doc: https://docs.google.com/document/d/18cKMC2UKTrJQ41vIWskcPLfB5BslRLSvy8dxP_BHcI0/edit?usp=sharing

**Comment by alanchangxyz** [comment]
Pulling this back to in-progress while we work on the recommendations from dsgn for now
